feature: Conceptial improvements for namespace
eclipse-esmf/esmf-sdk pull request #425
Opened 2023-09-19 07:10 UTC by Yauhenikapl

Changes:
- Update basic code for supporting new Entity - Namespace after release meta-model version 2.2.0.

#10898

2023-09-26 08:36 UTC, atextor requested changes

2023-09-26 08:36 UTC, atextor commented on core/esmf-aspect-meta-model-java/src/main/java/org/eclipse/esmf/metamodel/Namespace.java
> +public interface Namespace extends StructureElement {
This should not extends StructureElement; since it does not have Properties like Aspects and Entities.

2023-09-26 08:36 UTC, atextor commented on core/esmf-aspect-model-document-generators/src/main/java/org/eclipse/esmf/aspectmodel/generator/diagram/AspectModelDiagramGenerator.java
> +      //TODO: Add new version of SAMM 2.2.0
This might not be necessary _if_ #407 is merged before.

2024-07-12 08:41 UTC, Yauhenikapl commented
I was done in the separate task: #602

2024-07-12 08:41 UTC, closed without merging