bugfix: Example json Payload generated as plain value but should be array
eclipse-esmf/esmf-sdk pull request #486
Opened 2023-12-01 13:39 UTC by Yauhenikapl

Changes:

- Fix AspectModelJsonPayloadGenerator;

Fixes #423

2023-12-06 07:06 UTC, Yauhenikapl commented on core/esmf-aspect-model-document-generators/src/main/java/org/eclipse/esmf/aspectmodel/generator/json/AspectModelJsonPayloadGenerator.java
> +      return trait.getBaseCharacteristic().is( Collection.class ) && (trait.getConstraints().size() == 1);
You are totally right and I will fix it. But in our current realization works ))

Thank you!

2023-12-07 08:24 UTC, KobOp approved these changes

2023-12-07 10:08 UTC, atextor requested changes

2023-12-08 12:02 UTC, atextor approved these changes

2023-12-11 05:52 UTC, merged