Create Aspect Models from AAS submodel template
eclipse-esmf/esmf-sdk pull request #517
Opened 2024-01-29 11:35 UTC by Yauhenikapl

Changes:
- Add new command for AAS submodels generation;
- Update AAS Generator.

Fixes: #468

2024-02-07 13:44 UTC, atextor requested changes

2024-02-07 13:44 UTC, atextor commented on tools/samm-cli/src/main/java/org/eclipse/esmf/aas/AasListSubmodelsCommand.java
> +      if ( !extension.equals( "xml" ) && !extension.equals( "json" ) && !extension.equals( "aasx" ) ) {
Not necessary, but only a suggestion:

```suggestion
      if ( Arrays.stream( AasFileFormat.values() ).anyMatch( format -> format.toString().equals( extension ) ) ) {
```

2024-02-07 13:44 UTC, atextor commented on tools/samm-cli/src/main/java/org/eclipse/esmf/aas/AasListSubmodelsCommand.java
> +         throw new CommandException( "Input file name must be an .xml, .aasx or .json file" );
Suggestion:

```suggestion
         throw new CommandException( "Input file name must be one of " + AasFileFormat.allValues() );
```

2024-02-07 13:44 UTC, atextor commented on tools/samm-cli/src/main/java/org/eclipse/esmf/aas/AasListSubmodelsCommand.java
> +      List<String> submodelNames = AasToAspectModelGenerator.fromFile( new File( path ) ).getSubmodelNames();
```suggestion
      final List<String> submodelNames = AasToAspectModelGenerator.fromFile( new File( path ) ).getSubmodelNames();
```

2024-02-07 13:44 UTC, atextor commented on tools/samm-cli/src/main/java/org/eclipse/esmf/aas/AasListSubmodelsCommand.java
> +      }
```suggestion
      for ( final String submodelName : submodelNames ) {
         final int index = submodelNames.indexOf( submodelName );
         System.out.printf( "%2s: %s%n", index + 1, submodelName );
      }
```

2024-02-07 13:44 UTC, atextor commented on tools/samm-cli/src/main/java/org/eclipse/esmf/aas/to/AasToAspectCommand.java
> +         description = "Select one or a few options for generation an Aspect Model from AAS. Before run 'list' command for getting possible options." )
```suggestion
         description = "Select the submodel template(s) to include, as returned by the aas list command" )
```

2024-02-13 12:51 UTC, atextor requested changes

2024-02-13 12:51 UTC, atextor commented on documentation/developer-guide/modules/tooling-guide/pages/samm-cli.adoc
> +                                       Asset Administration Shell (AAS) file.                                                | `samm ass AssetAdminShell.aasx list`
```suggestion
                                       Asset Administration Shell (AAS) file.                                                | `samm aas AssetAdminShell.aasx list`
```

2024-02-13 12:51 UTC, atextor commented on tools/samm-cli/src/test/java/org/eclipse/esmf/ProcessLauncher.java
> +   public static record ExecutionResult(int exitStatus, String stdout, String stderr, byte[] stdoutRaw, byte[] stderrRaw) {
Undo these changes; it seems the formatting style is up to date. I'll have a look at https://github.com/eclipse-esmf/esmf-sdk/issues/25 for this.

2024-02-13 13:30 UTC, Yauhenikapl commented on documentation/developer-guide/modules/tooling-guide/pages/samm-cli.adoc
> +                                       Asset Administration Shell (AAS) file.                                                | `samm ass AssetAdminShell.aasx list`
Oh my God... 
Sorry for this...

2024-02-13 13:44 UTC, atextor approved these changes

2024-02-13 14:12 UTC, merged