515 extended static metamodel functionality
eclipse-esmf/esmf-sdk pull request #521
Opened 2024-02-02 14:42 UTC by andreas-schilling

2024-02-02 14:43 UTC, andreas-schilling commented
The documentation part is yet missing, however the code part can already be reviewed.

2024-02-16 12:31 UTC, atextor requested changes

2024-02-16 12:31 UTC, atextor commented on documentation/developer-guide/modules/static-metaclasses/pages/advanced-usage.adoc
> +the `Predicates` utility from the awesome https://docs.vavr.io[Vavr] library.
```suggestion
the `Predicates` utility from the https://docs.vavr.io[Vavr] library.
```

2024-02-19 07:04 UTC, atextor approved these changes

2024-02-19 07:55 UTC, merged