Add property to skip plugin execution
eclipse-esmf/esmf-sdk pull request #627
Opened 2024-07-22 14:26 UTC by MelleD

## Description

Add property to skip plugin execution

Fixes #624
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Additional notes:

Add any other notes or comments here.

2024-07-25 05:25 UTC, atextor requested changes
Please also mention/explain the `<skip>` parameter in maven-plugin.adoc.

2024-07-25 12:44 UTC, MelleD commented
> Member

done

2024-07-26 07:29 UTC, atextor approved these changes

2024-07-26 07:30 UTC, Yauhenikapl approved these changes

2024-07-26 07:34 UTC, merged