Add heading SAMM CLI List of commands to samm-cli.adoc
eclipse-esmf/esmf-sdk pull request #639
Opened 2024-08-07 07:53 UTC by chris-volk

Add SAMM CLI List of commands as a subheading for better structure. This allows a deeplink to the command list without scrolling. Quicker reference for people who may not know that there is a list of commands on this page

## Description

Please include a summary of the changes and the related issue. List any dependencies that are required for this change.

Fixes #(number of issue in GitHub)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Additional notes:

Add any other notes or comments here.

2024-08-07 08:02 UTC, atextor requested changes

2024-08-07 08:02 UTC, atextor commented on documentation/developer-guide/modules/tooling-guide/pages/samm-cli.adoc
> +=== SAMM CLI List of commands
IMO this can be simplified:
```suggestion
=== List of commands
```

2024-08-14 06:48 UTC, Yauhenikapl approved these changes

2024-08-14 08:01 UTC, atextor approved these changes

2024-08-14 08:01 UTC, merged