Update SQL generator for handling collections of entities
eclipse-esmf/esmf-sdk pull request #692
Opened 2024-12-17 13:44 UTC by Yauhenikapl

## Description

Update SQL generator for handling collections of entities

Fixes #622 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

## Additional notes

2024-12-18 07:14 UTC, atextor requested changes

2024-12-18 07:14 UTC, atextor commented on core/esmf-aspect-model-document-generators/src/test/java/org/eclipse/esmf/aspectmodel/generator/sql/databricks/AspectModelDatabricksDenormalizedSqlVisitorTest.java
> +              entity_property_two STRING NOT NULL
This change is not correct; the nested structure of `myPropertyOne`/`entityPropertyOne` still needs to be present, but flattened by name concatenation. I.e., this line should read:
`my_property_one__entity_property_one__entity_property_two STRING NOT NULL`

2024-12-18 07:14 UTC, atextor commented on core/esmf-aspect-model-document-generators/src/test/java/org/eclipse/esmf/aspectmodel/generator/sql/databricks/AspectModelDatabricksDenormalizedSqlVisitorTest.java
> +              nested_entity_property STRING NOT NULL
Like in my other comment, the structure still needs to be present, so this should be:
`test_property__nested_entity_property STRING NOT NULL`

2025-01-07 16:00 UTC, atextor requested changes

2025-01-08 06:13 UTC, Yauhenikapl commented on core/esmf-aspect-model-document-generators/src/test/java/org/eclipse/esmf/aspectmodel/generator/sql/databricks/AspectModelDatabricksDenormalizedSqlVisitorTest.java
> +              random_value STRING NOT NULL
Yes, ty!
Have to fix it!

2025-01-13 07:09 UTC, atextor approved these changes

2025-01-13 07:09 UTC, merged